# Generated by Django 5.0.6 on 2024-06-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_aktor_extrainfo_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horror'), (3, 'Sci-fi'), (0, 'Inne'), (2, 'Komedia'), (4, 'Dramat')], null=True),
        ),
    ]
