# Generated by Django 5.0.6 on 2024-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0006_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Inne'), (4, 'Dramat'), (2, 'Komedia'), (3, 'Sci-fi'), (1, 'Horror')], null=True),
        ),
    ]
